sudo: required
services:
  - docker
before_install
  - openssl aes-256-cbc -K $encrypted_9ed3b022f8a8_key -iv $encrypted_9ed3b022f8a8_iv -in multi-k8s-2-365013-4cd8336f48ac.json.enc -out multi-k8s-2-365013-4cd8336f48ac.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download and install
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json #allow travis ci to access google cloud something like aws IAM

